version: "2.2"

services:
  nginx:
    image: nginx:alpine
    working_dir: /app
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./containers/nginx/conf/conf.d/:/etc/nginx/conf.d
      - ../:/app
      - ../var/log/:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build:
      context:
        ./containers/php-fpm
    image: php-fpm:last
    working_dir: /app
    volumes:
      - ./containers/php-fpm/conf/my.ini:/usr/local/etc/php/conf.d/my.ini
      - ../:/app
      - ../var/log/:/var/log/php-fpm
      - ./.bash_history:/root/.bash_history
    links:
      - redis
    expose:
      - 10000 #for xdebug
    environment:
      PROMPT_COMMAND: history -a;history -r
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      REMOTE_CONNECT_BACK: ${REMOTE_CONNECT_BACK}

  redis:
    image: redis:4-alpine
